baseURL = 'https://lex-research-notebook.netlify.app/'
languageCode = "en-us"
title = "Research Notebook"
theme = "personal-web"
copyright="©LexCaldwell"
googleAnalytics = ""
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true

[params.intro]
  main = "Research Notebook"

[params.main]
  latestPublishHeader = "My Latest Project"

[taxonomies]
  design = "designs"
  tech = "techs"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['portfolio']

[params.notFound]
  gopher = "/images/gopher.png"
  h1 = 'Bummer!'
  p = "It seems that this page doesn't exist."

[params.sections]
  post = "article"
  portfolio = "project"

[params.sidebar]
  backgroundImage = ''
  gradientOverlay = ''
  logo = ""

[params.assets]
  favicon = ""
  customCSS = ""

[params.social]
  github = "https://github.com/"

[params.contact]
  email = ""
  text= ""


[menu]

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false